#ifndef POKEPLATINUM_CONSTANTS_TOTEM_BATTLE_H
#define POKEPLATINUM_CONSTANTS_TOTEM_BATTLE_H

#define TOTEM_ENCOUNTER_HITMONLEE   0
#define TOTEM_ENCOUNTER_VESPIQUEN   1
#define TOTEM_ENCOUNTER_SPIRITOMB   2
#define TOTEM_ENCOUNTER_SKARMORY    3
#define TOTEM_ENCOUNTER_LAPRAS      4
#define TOTEM_ENCOUNTER_AGGRON      5
#define TOTEM_ENCOUNTER_MAMOSWINE   6
#define TOTEM_ENCOUNTER_KINGDRA     7
#define TOTEM_ENCOUNTER_COUNT       8

#define TOTEM_PARTY_SIZE       3
#define TOTEM_MAX_ALLY_SUMMONS 2

#endif // POKEPLATINUM_CONSTANTS_TOTEM_BATTLE_H
