import sys
sys.dont_write_bytecode = True
sys.path.insert(0, '/tmp/a1r3/tools')
from dschars import *

# ================================================================ Darren (boy): teal jacket, dark curly hair, dark skin
BOY = Design('boy', {
    'hair': [(132, 92, 66), (90, 58, 42), (54, 36, 30)],
    'skin': [(208, 148, 102), (172, 112, 74), (126, 78, 52)],
    'top': [(118, 212, 188), (58, 158, 142), (30, 102, 100)],
    'top2': [(248, 248, 240), (196, 202, 210)],
    'bottom': [(86, 90, 118), (58, 60, 86)],
    'shoes': [(132, 70, 60), (132, 70, 60)],
}, {
    'down': """
......HHHHH......
....HHHHHHHHH....
...HHHHHHHHHHH...
..HHHHHHHHHHHHH..
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHFHHHHHFHHHH.
.HHFFFFFFFFFFFHH.
.HHFFFFFFFFFFFHH.
..HFFFFFFFFFFFH..
...FFFFFFFFFFF...
....FFFFFFFFF....
....TTJFFFJTT....
..UUTTJJJJJTTUU..
.UUUTTTJJJTTTUUU.
.hhUUTTTJTTTUUhh.
.hhh.TTTJTTT.hhh.
....TTTTTTTTT....""",
    'up': """
......HHHHH......
....HHHHHHHHH....
...HHHHHHHHHHH...
..HHHHHHHHHHHHH..
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
..HHHHHHHHHHHHH..
...HHHHHHHHHHH...
....FHHHHHHHF....
....TTTFFFTTT....
..UUTTTTTTTTTUU..
.UUUTTTTTTTTTUUU.
.hhUUTTTTTTTUUhh.
.hhh.TTTTTTT.hhh.
....TTTTTTTTT....""",
    'left': """
.....HHHHHH......
...HHHHHHHHHH....
..HHHHHHHHHHHH...
.HHHHHHHHHHHHHH..
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHFHHHHHHHHHHH.
.HFFFFFHHHHHHHHH.
..FFFFFFHHHHHHH..
..FFFFFFFHHHHH...
..FFFFFFFFHHH....
...FFFFFFFF......
.....FFFFTT......
.....JTTTTT......
....JTTUUTT......
....JTTUUTT......
....JTThhTT......
.....TTTTTT......""",
}, {
    'down': """
.................
.................
.....a....a......
....aba..aba.....
...a.b.....b..a..
.................
.....b.....b.....
.................
.................
.....k.....k.....
.....c.....c.....
.................
.......zzz.......
.................
.......u.........
.......kk........
.................
........k........
.................""",
    'up': """
.................
.................
.....a....a......
....aba..aba.....
...a.b.....b..a..
.................
....b..b..b..b...
.................
...b...b...b..b..
.................
.................
.................
.................
.................
.................
.................
.................
.................
.................""",
    'left': """
.................
.................
....a....a.......
...aba..aba......
..a.b.....b......
.................
.................
....b............
.................
...k.............
...c.............
.................
.................
.................
.................
.................
.................
.................
.................""",
})
