import sys
sys.dont_write_bytecode = True
sys.path.insert(0, '/tmp/a1r3/tools')
from dschars import *

PANTS_LEGS = LEGS

SKIRT_LEGS = {
    'down': {
        'stand': """
..PPPPPPPPPPPPP..
.....GGG.GGG.....
.....GGG.GGG.....
.....MMM.MMM.....""",
        'stepA': """
...PPPPPPPPPPP...
..PPPPPPPPPPPPP..
.....GGG.GGG.....
.....MMM.GGG.....
.........GGG.....
.........MMM.....""",
        'stepB': """
...PPPPPPPPPPP...
..PPPPPPPPPPPPP..
.....GGG.GGG.....
.....GGG.MMM.....
.....GGG.........
.....MMM.........""",
    },
    'left': {
        'stand': """
...PPPPPPPPPP....
.....GGGG........
.....GGGG........
....MMMMM........""",
        'stepA': """
...PPPPPPPPP.....
..PPPPPPPPPPP....
...GGG...GGG.....
..GGG....GGG.....
.MMMM....GGG.....
.........MMMM....""",
        'stepB': """
...PPPPPPPPP.....
..PPPPPPPPPPP....
....GGG.GGG......
....GGG.GGG......
...MMMM.MMMM.....
.................""",
    },
}
SKIRT_LEGS['up'] = SKIRT_LEGS['down']

COAT_LEGS = {
    'down': {
        'stand': """
...TTTTTTTTTTT...
.....PPP.PPP.....
.....PPP.PPP.....
.....MMM.MMM.....""",
        'stepA': """
...TTTTTTTTTTT...
...TTTTTTTTTTT...
.....PPP.PPP.....
.....MMM.PPP.....
.........PPP.....
.........MMM.....""",
        'stepB': """
...TTTTTTTTTTT...
...TTTTTTTTTTT...
.....PPP.PPP.....
.....PPP.MMM.....
.....PPP.........
.....MMM.........""",
    },
    'left': {
        'stand': """
...TTTTTTTTT.....
.....PPPP........
.....PPPP........
....MMMMM........""",
        'stepA': """
...TTTTTTTTT.....
...TTTTTTTTTT....
...PPP...PPP.....
..PPP....PPP.....
.MMMM....PPP.....
.........MMMM....""",
        'stepB': """
...TTTTTTTTT.....
...TTTTTTTTTT....
....PPP.PPP......
....PPP.PPP......
...MMMM.MMMM.....
.................""",
    },
}
COAT_LEGS['up'] = COAT_LEGS['down']

# ================================================================ Darren (boy)
BOY = Design('boy', {
    'hair': [(140, 98, 70), (92, 60, 44), (54, 36, 30)],
    'skin': [(208, 148, 102), (172, 112, 74), (126, 78, 52)],
    'top': [(118, 212, 188), (58, 158, 142), (30, 102, 100)],
    'top2': [(248, 248, 240), (196, 202, 210)],
    'bottom': [(86, 90, 118), (58, 60, 86)],
    'shoes': [(150, 76, 62), (150, 76, 62)],
}, {
    'down': """
......HHHHH......
....HHHHHHHHH....
...HHHHHHHHHHH...
..HHHHHHHHHHHHH..
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHFHHHHHFHHHH.
.HHFFFFFFFFFFFHH.
.HHFFFFFFFFFFFHH.
..HFFFFFFFFFFFH..
...FFFFFFFFFFF...
....FFFFFFFFF....
....TTJFFFJTT....
..UUTTJJJJJTTUU..
.UUUTTTJJJTTTUUU.
.hhUUTTTJTTTUUhh.
.hhh.TTTJTTT.hhh.
....TTTTTTTTT....""",
    'up': """
......HHHHH......
....HHHHHHHHH....
...HHHHHHHHHHH...
..HHHHHHHHHHHHH..
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
..HHHHHHHHHHHHH..
...HHHHHHHHHHH...
....FHHHHHHHF....
....TTTFFFTTT....
..UUTTTTTTTTTUU..
.UUUTTTTTTTTTUUU.
.hhUUTTTTTTTUUhh.
.hhh.TTTTTTT.hhh.
....TTTTTTTTT....""",
    'left': """
.....HHHHHH......
...HHHHHHHHHH....
..HHHHHHHHHHHH...
.HHHHHHHHHHHHHH..
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHFHHHHHHHHHHH.
.HFFFFFHHHHHHHHH.
..FFFFFFHHHHHHH..
..FFFFFFFHHHHH...
..FFFFFFFFHHH....
...FFFFFFFF......
.....FFFFTTT.....
....JTTTTTTTT....
...JTTTUUUTTT....
...JTTTUUUTTT....
...JTTThhhTTT....
....TTTTTTTT.....""",
}, {
    'down': """
.................
.................
.....a..a..a.....
....aba.b.aba....
...b.b.aba.b.b...
..ab.b..b..b.ba..
..b.ab.ab.ab..b..
..c..b..b..b..c..
.................
.....k.....k.....
.....c.....c.....
.................
.......zzz.......
.................
.......u.........
.......kk........
..x...........x..
..x.....k.....x..
.................""",
    'up': """
.................
.................
.....a..a..a.....
....aba.b.aba....
...b.b.aba.b.b...
..ab.b..b..b.ba..
..b.ab.ab.ab..b..
..c..b..b..b..c..
..b.ab.ab.ab.cb..
..c..c..c..c..c..
...c..c...c..c...
.................
.................
.................
.................
.................
..x...........x..
..x...........x..
.................""",
    'left': """
.................
.................
....a..a.........
...aba.b.a.......
..b.b.aba.b.b....
..ab..b..b.ba.b..
..b.ab.ab.ab..b..
.....b..b..b.c...
.........cb.c....
...k......c......
...c.............
.................
.................
.................
.................
.................
.................
........x........
.................""",
})

# ================================================================ Darren (girl)
GIRL = Design('girl', {
    'hair': [(190, 228, 250), (124, 180, 236), (70, 112, 188)],
    'skin': [(252, 222, 194), (240, 186, 154), (200, 136, 112)],
    'top': [(250, 250, 252), (210, 222, 242), (150, 166, 210)],
    'top2': [(92, 140, 226), (52, 92, 180)],
    'bottom': [(100, 128, 210), (66, 84, 158)],
    'shoes': [(70, 76, 140), (70, 76, 140)],
}, {
    'down': """
.......HHH.......
......HHHHH......
.....HHHHHHH.....
....HHHHHHHHH....
...HHHHHHHHHHH...
..HHHHHHHHHHHHH..
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHFFHHHHHFFHHH.
.HHFFFFFFFFFFFHH.
.HHFFFFFFFFFFFHH.
.HHFFFFFFFFFFFHH.
.HHHFFFFFFFFFHHH.
.HHH.FFFFFFF.HHH.
..HH.TJJFJJT.HH..
..UUTTJJJJJTTUU..
.UUUTTTJJJTTTUUU.
.hhUTTTTTTTTTUhh.
.hhh.TTTTTTT.hhh.
...PPPPPPPPPPP...""",
    'up': """
.......HHH.......
......HHHHH......
.....HHHHHHH.....
....HHHHHHHHH....
...HHHHHHHHHHH...
..HHHHHHHHHHHHH..
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
..HHHHHHHHHHHHH..
..UUTHHHHHHHTUU..
.UUUTTHHHHHTTUUU.
.hhUTTTTTTTTTUhh.
.hhh.TTTTTTT.hhh.
...PPPPPPPPPPP...""",
    'left': """
...........HHH...
.........HHHHHH..
......HHHHHHHHH..
....HHHHHHHHHHH..
...HHHHHHHHHHHH..
..HHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
.HHFFHHHHHHHHHHH.
.HFFFFFHHHHHHHHH.
..FFFFFFHHHHHHH..
..FFFFFFFHHHHHH..
..FFFFFFFFHHHHH..
...FFFFFFFHHHH...
.....FFTTTHH.....
....JTTTTTTT.....
....JTTUUUTT.....
....TTTUUUTT.....
....TTThhhTT.....
...PPPPPPPPP.....""",
}, {
    'down': """
.......a.........
......aab........
.....ab.b........
....a.b..b.......
...ab.b.a.b.b....
..a.bb.aba.bb.b..
..b.b..b...b.bc..
..cb.b.b..b.b.c..
..c.c..c...c..c..
...c.......c.....
.....k.....k.....
.....k.....k.....
.................
..c...........c..
..c...........c..
...c.........c...
.......t.t.......
.......utu.......
..x...........x..
..x...........x..
.................""",
    'up': """
.......a.........
......aab........
.....aub.........
....a.uu.b.......
...ab.b.a.b.b....
..a.bb.aba.bb.b..
..b.b..b...b.bc..
..b.b.bb.b.b.bc..
..b.bb.b.bb.b.c..
..b.b..b.b..b.c..
..cb.b.b..b.bcc..
..c.bb.b.bb.c.c..
..cc.b.bb.b.c.c..
..c.c.cb.b.c.cc..
..cc.c.c.c.c.c...
...cc.c.c.c.cc...
.................
.................
..x...........x..
..x...........x..
.................""",
    'left': """
...........ab....
.........aab.b...
......a.ab.bb....
....aab.b.bbc....
...ab.b.aab.bc...
..a.bb.aa.bb.bc..
..b.b...bb.b.bc..
..c....b..b.bcc..
..c...b..bb.b.c..
...c...b...b.cc..
.......b..b.cc...
.......c.b.ccc...
..k......c.cc....
..k.......cc.....
.........cc......
.................
.................
.................
.................
........x........
.................""",
}, legs=SKIRT_LEGS)

# ================================================================ Garius (rival)
GARIUS_PAL = {
    'hair': [(204, 110, 100), (152, 62, 66), (96, 36, 44)],
    'skin': [(250, 214, 178), (230, 170, 130), (182, 114, 90)],
    'top': [(246, 100, 90), (202, 50, 58), (130, 28, 40)],
    'top2': [(74, 66, 76), (46, 42, 50)],
    'bottom': [(82, 82, 98), (54, 54, 66)],
    'shoes': [(170, 170, 180), (170, 170, 180)],
}
GARIUS_GRIDS = {
    'down': """
...H.....H....H..
...HH...HH...HH..
...HHH.HHHH.HHH..
..HHHHHHHHHHHHH..
..HHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
.HHHHHHHHHHHHHHHH
.HHHHHHHHHHHHHHH.
HHHHHHHHHHHHHHHHH
.HHHFHHHHFHHHFHH.
.HHFFFFFFFFFFFHH.
..HFFFFFFFFFFFH..
..HFFFFFFFFFFFH..
...FFFFFFFFFFF...
....FFFFFFFFF....
....TTTFFFTTT....
..UUTTJJJJJTTUU..
.UUUTTTTTTTTTUUU.
.hhUUTTTTTTTUUhh.
.hhh.TTTTTTT.hhh.
....JJJJJJJJJ....""",
    'up': """
...H.....H....H..
...HH...HH...HH..
...HHH.HHHH.HHH..
..HHHHHHHHHHHHH..
..HHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
.HHHHHHHHHHHHHHHH
.HHHHHHHHHHHHHHH.
HHHHHHHHHHHHHHHHH
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
..HHHHHHHHHHHHH..
..HHHHHHHHHHHHH..
...HHHHHHHHHHH...
....FHHHHHHHF....
....TTTFFFTTT....
..UUTTTTTTTTTUU..
.UUUTTTTTTTTTUUU.
.hhUUTTTTTTTUUhh.
.hhh.TTTTTTT.hhh.
....JJJJJJJJJ....""",
    'left': """
.......H....H....
.......HH..HH...H
....HHHHHHHHH.HH.
...HHHHHHHHHHHHH.
..HHHHHHHHHHHHHHH
.HHHHHHHHHHHHHHH.
HHHHHHHHHHHHHHHHH
.HHHHHHHHHHHHHHHH
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHHH
.HFFHHHHHHHHHHHH.
.HFFFFFHHHHHHHH..
..FFFFFFHHHHHHH..
..FFFFFFFHHHHH...
..FFFFFFFFHHH....
...FFFFFFFF......
.....FFFFTTT.....
....TTTTTTTTT....
...TTTTUUUTTT....
...TTTTUUUTTT....
...TTTThhhTTT....
....JJJJJJJJ.....""",
}
GARIUS_DET = {
    'down': """
.................
...a.....a....a..
....a...ab...ab..
...a.ab.a.b.ab...
...ab.aab.bab.b..
..a.bab.ab.ab.bb.
..b..ab..b..b.b..
..ab.b.ab.ab.bc..
..b.b..b..b..b...
..c.b.cb.cb.c.c..
...c..c....c.....
.................
.....k.....k.....
.....k.....k.....
.................
.................
.................
.................
.................
..x...........x..
..x...........x..
.................""",
    'up': """
.................
...a.....a....a..
....a...ab...ab..
...a.ab.a.b.ab...
...ab.aab.bab.b..
..a.bab.ab.ab.bb.
..b..ab..b..b.b..
..ab.b.ab.ab.bc..
..b.b..b..b..b...
..c.b.cb.cb.c.c..
...b..b.b..b.bc..
..cb.cb.cb.cb.c..
...c..c..c..c....
....c..c..c..c...
.................
.................
.................
.................
.................
..x...........x..
..x...........x..
.................""",
    'left': """
.................
........a...a....
.....a.a.b.ab..a.
....ab.ab.ab.ab..
...a.ab.ab.ab.bb.
..a.bab.ab.ab.b..
..b..ab..b..b.bb.
...ab.b.ab.ab.bc.
..b.b..b..b..bc..
..c.c....cb.c.c..
.................
.................
..k..............
..k..............
.................
.................
.................
.................
.................
.................
........x........
.................""",
}
GARIUS = Design('garius', GARIUS_PAL, GARIUS_GRIDS, GARIUS_DET)
ECLIPSE_PAL = dict(GARIUS_PAL)
ECLIPSE_PAL.update({
    'hair': [(112, 108, 140), (72, 68, 100), (42, 38, 62)],
    'top': [(184, 128, 238), (132, 76, 198), (82, 42, 132)],
    'top2': [(60, 44, 84), (36, 26, 52)],
    'bottom': [(58, 52, 76), (38, 34, 52)],
    'shoes': [(120, 112, 140), (120, 112, 140)],
})
GARIUS_ECLIPSE = Design('garius_eclipse', ECLIPSE_PAL, GARIUS_GRIDS, GARIUS_DET)

# ================================================================ Ruth (assistant)
RUTH = Design('ruth', {
    'hair': [(190, 142, 236), (136, 86, 200), (86, 48, 140)],
    'skin': [(252, 222, 194), (240, 186, 154), (200, 136, 112)],
    'top': [(252, 252, 252), (214, 218, 232), (156, 160, 186)],
    'top2': [(176, 210, 246)],
    'acc': [(222, 62, 70)],
    'bottom': [(74, 66, 90), (50, 46, 62)],
    'shoes': [(140, 92, 66), (140, 92, 66)],
}, {
    'down': """
.....HHHHHH......
...HHHHHHHHHH....
..HHHHHHHHHHHH...
.HHHHHHHHHHHHHH..
.HHHHHHHHHHHHHHH.
HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
HHHHFFHHHHFFFHHHH
HHHFFFFFFFFFFFHHH
HHHFFFFFFFFFFFHHH
HHHFFFFFFFFFFFHHH
HHHHFFFFFFFFFHHHH
.HHH.FFFFFFF.HHH.
.HHHTTJFFFJTTHHH.
..UUTTJXXXJTTUU..
.UUUTTJJXJJTTUUU.
.hhUTTTJXJTTTUhh.
.hhh.TTJJJTTT.hhh
...TTTTTTTTTTT...""",
    'up': """
.....HHHHHH......
...HHHHHHHHHH....
..HHHHHHHHHHHH...
.HHHHHHHHHHHHHH..
.HHHHHHHHHHHHHHH.
HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
.HHHHHHHHHHHHHHH.
.HHHHHHHHHHHHHHH.
..UUTHHHHHHHTUU..
.UUUTTHHHHHTTUUU.
.hhUTTTTTTTTTUhh.
.hhh.TTTTTTTT.hhh
...TTTTTTTTTTT...""",
    'left': """
....HHHHHHH......
..HHHHHHHHHHH....
.HHHHHHHHHHHHH...
.HHHHHHHHHHHHHH..
HHHHHHHHHHHHHHHH.
HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH
.HHFFHHHHHHHHHHHH
.HFFFFFHHHHHHHHHH
..FFFFFFHHHHHHHHH
..FFFFFFFHHHHHHHH
..FFFFFFFFHHHHHH.
...FFFFFFFHHHHHH.
.....FFFFHHHHH...
....JTTTTTHHH....
...XJTTUUUTT.....
...JTTTUUUTT.....
...TTTTUUUTT.....
...TTTThhhTT.....
...TTTTTTTTT.....""",
}, {
    'down': """
.................
.....a..a........
...aab.ab.a......
..a.b.ab.ab.b....
..ab.bb.b.bb.b...
.a.bb.ab.ab.bbb..
.b.b..b..b..b.bc.
.cb.b.b.b..b.bc..
.cc.k.kkkkkk.c.c.
.c.kwkk...kwkc...
.c..k.k...k.kc...
.cc.k.......k.c..
..c.c.......c.c..
..cc.........cc..
..c...........c..
.................
.................
..x...........x..
..x...........x..
.................""",
    'up': """
.................
.....a..a........
...aab.ab.a......
..a.b.ab.ab.b....
..ab.bb.b.bb.b...
.a.bb.ab.ab.bbb..
.b.b..b..b..b.bc.
.bb.b.b.b..b.bc..
.b.bb.bb.b.bb.cb.
.cb.b..b.b..b.c..
.bc.bb.b.bb.bcc..
.cb.b.b.b.b.c.c..
.cc.c.cb.b.c.cc..
..cc.c.c.c.c.c...
..cc..c.c.c.cc...
.................
.................
..x...........x..
..x...........x..
.................""",
    'left': """
.................
....a..a.........
..aab.ab.a.......
..a.b.ab.ab.b....
.ab.bb.b.bb.b.c..
.a.bb.ab.ab.bbbc.
.b.b..b..b..b.bc.
..k..b.b.b..b.bc.
.kwk..b...b.bcc..
..k.......b.bc...
..........c.cc...
..........cc.c...
..........ccc....
.................
.................
.................
.................
.................
........x........
.................""",
}, legs=COAT_LEGS)

CAST = [BOY, GIRL, GARIUS, GARIUS_ECLIPSE, RUTH]
